# Generated by Django 4.1.6 on 2023-02-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('fever', models.FloatField()),
                ('body_pain', models.IntegerField(help_text='0-No Pain, 1-Severe Pain')),
                ('runny_nose', models.IntegerField(help_text='0-No, 1-Yes')),
                ('diff_breath', models.IntegerField(help_text='-1-No Difficulty, 0-Medium Difficulty, 1-Severe Difficulty')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('used_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_consumption',
            },
        ),
        migrations.AddIndex(
            model_name='userconsumption',
            index=models.Index(fields=['id'], name='user_consum_id_ac9def_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='user_id_f1790c_idx'),
        ),
    ]
