# Generated by Django 4.1.6 on 2023-02-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_created_at_remove_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='body_pain',
            field=models.IntegerField(help_text='0-No Pain, 1-Severe Pain'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diff_breath',
            field=models.IntegerField(help_text='-1-No Difficulty, 0-Medium Difficulty, 1-Severe Difficulty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='runny_nose',
            field=models.IntegerField(help_text='0-No, 1-Yes'),
        ),
    ]
